name: task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  loader_overlay: ^4.0.0
  fluentui_system_icons: ^1.1.226
  google_maps_flutter: ^2.5.3
  status_bar_control: ^3.2.1
  lottie: ^3.0.0


  #Fetch API
  dio: ^5.4.0

  #State management
  get: ^4.6.6
  get_it: ^7.6.7

  #Caching
  get_storage: ^2.1.1

  #Tools
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_polyline_points: ^2.0.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
